### ISSUE TITLE
looking forward to your outstanding work

### ISSUE THREAD

**Issue by nicebro123** [lambert-x/medical_mae#1]

**Comment by Xglbrilliant** [comment]
me too.

**Comment by lambert-x** [comment]
Code will be released in the next two weeks.

**Comment by Romelia0712** [comment]
Dear author, I have benefited a lot from your research. I have a deep respect for you. I have a question to ask you, which code is used to realize the recomposition in your article.

**Comment by lambert-x** [comment]
> Dear author, I have benefited a lot from your research. I have a deep respect for you. I have a question to ask you, which code is used to realize the recomposition in your article.

I am not sure if you are discussing about visualizing the reconstruction. If yes, please refer to the [jupyter notebook from MAE official](https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb)
