### ISSUE TITLE
Training codes of DN121 (82.2 mAUC)

### ISSUE THREAD

**Issue by JingfengYao** [lambert-x/medical_mae#10]
Hi, I am a little confused about the finetuning of DenseNet121.
I tried to reproduce DenseNet121 (ImageNet pre-trained) but failed to get the 82.2 mAUC while succeeded in DenseNet121(MAE). From pre-trained checkpoints, it seems that you finetune DN121(ImageNet) and DN121(MAE) with different codes. Because I have noticed that checkpoints in DN121(ImageNet) and DN121 (MAE) are like:
```
checkpoint = torch.load('densenet121_imagenet_torchvision.pth.tar')
print(checkpoint.keys())
# output:
# dict_keys(['epoch', 'lossMIN', 'state_dict', 'optimizer', 'scheduler'])
```
```
checkpoint = torch.load('densenet121_CXR_0.3M_mae.pth')
print(checkpoint.keys())
# output:
# dict_keys(['model', 'optimizer', 'epoch', 'scaler', 'args'])
```
Could you please tell me if it is correct and may I know more details about it?

**Comment by lambert-x** [comment]
Sorry for the late reply. I trained the torchvision checkpoint with this codebase: [https://github.com/PhoenixMark0/ChestX-ray14-Classification/tree/main/pytorch_code](https://github.com/PhoenixMark0/ChestX-ray14-Classification/tree/main/pytorch_code). You may modify the ckpt to make it compatible to this codebase. I think it is not that hard.
