### ISSUE TITLE
Image normalization

### ISSUE THREAD

**Issue by ieee8023** [lambert-x/medical_mae#11]
I'm working on running the models and I'm not sure about the image normalization. I have a notebook here that loads the MaskedAutoencoderCNN with the densenet121_CXR_0.3M_mae.pth weights and reconstructs an image. But the image does not appear reconstructed correctly. I've tried many normalizations but the area outside of the lungs appears blurry and the lungs appear reconstructed ok. Any idea what is wrong?

https://github.com/mlmed/torchxrayvision/blob/c44435011d97288e4af7d458dab95dc7ed6e6790/scripts/medical_mae_example.ipynb

Here is the PR to integrate it into torchxrayvision:
https://github.com/mlmed/torchxrayvision/pull/150

**Comment by lambert-x** [comment]
The image normalization settings are here: https://github.com/lambert-x/medical_mae/blob/5744fa572ec4b7f5bf3b4d241129f8393fac030e/main_pretrain_multi_datasets_xray.py#L147-L154

Could you please try it?

**Comment by ieee8023** [comment]
In that notebook I used 
```
torchvision.transforms.Normalize([0.5056, 0.5056, 0.5056], [0.252, 0.252, 0.252])
```

**Comment by lambert-x** [comment]
For plotting, I think you need to denormalize the output with the used mean and std.

**Comment by ieee8023** [comment]
matplotlib does its own linear normalization. The images should look the same with any mean and stdev adjustment.

Do you think you can modify that notebook to get the normalization correct?

**Comment by lambert-x** [comment]
Please refer to this function (I used for visualization before):

```
chestxray_mean = np.array([0.5056, 0.5056, 0.5056])
chestxray_std = np.array([0.252, 0.252, 0.252])

def show_image(image, title='', mean=chestxray_mean, std=chestxray_std):
    # image is [H, W, 3]
    assert image.shape[2] == 3
    plt.imshow(torch.clip((image * std + mean) * 255, 0, 255).int())
    plt.title(title, fontsize=16)
    plt.axis('off')
    print(title,'min:', image.min().item(),'max:', image.max().item())
    print(title,'mean:', image.mean().item(),'std:',  image.std().item())
    return
```

**Comment by ieee8023** [comment]
What does the rest of your code look like? The output of the densenet121_CXR_0.3M_mae.pth model was NCHW so I had to swap the axis. Are you using a different model?

<img width="356" alt="Screenshot 2024-03-13 at 17 10 36" src="https://github.com/lambert-x/medical_mae/assets/446367/184555e6-1bd7-4652-a7c3-d718798851e1">

**Comment by ieee8023** [comment]
Also, with the VIT model using unpatchify I'm getting a patchy artifact and blurry reconstructions. 

https://github.com/mlmed/torchxrayvision/blob/4fa907a53b9eb3ce722f833f1409f6099c38a63f/scripts/medical_mae_vit_example.ipynb

![image](https://github.com/lambert-x/medical_mae/assets/446367/b63c59d1-4080-4056-9ea5-69dcbbe0ce05)

**Comment by lambert-x** [comment]
Just uploaded a notebook for visualization. Please check https://github.com/lambert-x/medical_mae/blob/main/visualization.ipynb
