### ISSUE TITLE
GradCAM

### ISSUE THREAD

**Issue by BehzadBozorgtabar** [lambert-x/medical_mae#3]
Hi,

Can you please share your script for the GradCAM visualization for the ViT-s/16, figure 4, in the paper?

Thanks

**Comment by lambert-x** [comment]
Please refer to this notebook (the codes are a little bit dirty. Sorry about that) https://drive.google.com/file/d/1WG6zYHwaRbzTB0xbe28hKPJQmb0za8oT/view?usp=sharing
