### ISSUE TITLE
Pretraining Datesets

### ISSUE THREAD

**Issue by JingfengYao** [lambert-x/medical_mae#8]
Hi, thanks for the great work. 

I have a question you mentioned that NIH and CheXpert datasets have been used for both training and testing. I am curious about whether the images in the test sets have been used in the pretraining stage.

**Comment by lambert-x** [comment]
Just the training sets of both. You could check it with the dataloaders. https://github.com/lambert-x/medical_mae/blob/b199e6771f92a82ca524d63334a82e806b6db6d4/util/datasets.py#L65C1-L80C95
