### ISSUE TITLE
Finetuned Decoder Parameters

### ISSUE THREAD

**Issue by HarryHuangYZ** [lambert-x/medical_mae#9]
Hi there, I really appreciate your great work!

I have some questions regrading the replication. When I loaded the model weights and tried to visualize the result shown in the readme, I could not find the parameters for the decoder.

Also, these four variables cannot be found: 
head.weight not found in Init Model
head.bias not found in Init Model
fc_norm.weight not found in Init Model
fc_norm.bias not found in Init Model

 Could you please help me solve this issue? Could you also provide your code for visualizing Figure 2 in your paper? Thank you!

**Comment by lambert-x** [comment]
Please refer to this issue: https://github.com/lambert-x/medical_mae/issues/6
